### ISSUE TITLE
mac os vantura support

### ISSUE THREAD

**Issue by eth-man** [cliv/cs-falcon-protect-intune#4]
far as i know , script isn't working with Mac OS Vantura.

**Comment by cliv** [comment]
Can you provide more detail? It seems to be working for my users on Ventura, but there's always a chance I'm missing something.

**Comment by eth-man** [comment]
im not sure about it right now it was a call from HD team about it, ill try check it out

**Comment by cliv** [comment]
Closing for now due to lack of further info - Feel free to create a new issue once you have details.
