### ISSUE TITLE
Not a valid script error

### ISSUE THREAD

**Issue by jeffs1976** [cliv/cs-falcon-protect-intune#7]
When I upload CSFalconInstall.sh into Intune, I receive an error stating that it is not a valid script and am unable to proceed.  

![image](https://user-images.githubusercontent.com/123094111/213477387-a708e93d-d2e2-4918-9153-721960347deb.png)

**Comment by cliv** [comment]
You've saved an HTML file from github, not the raw script.

Save and upload https://raw.githubusercontent.com/cliv/cs-falcon-protect-intune/main/CSFalconInstall.sh instead - But make sure you edit it and put your own parameters into the script first.
