### ISSUE TITLE
Configure falcon Crowdstrike for InTune MacOS 

### ISSUE THREAD

**Issue by aloum** [cliv/cs-falcon-protect-intune#8]
I followed the steps to deploy the Falcon sensor to via InTune to our MacOS computer, and at the end of the steps it says to run the following Command“sudo /Applications/https://urldefense.proofpoint.com/v2/url?u=http-3A__Falcon.app_Contents_Resources_falconctl&d=DwIF-g&c=08AGY6txKsvMOP6lYkHQpPMRA1U6kqhAwGa8-0QCg3M&r=PFi52xEUDIqQVIo73arA1MxzkLx_6zMUVLjjX8gUzZI&m=F36OC2qrFeQwuCYnQqx4b6wc5QFalRAmi_4Apq1vmi8XmH7qOgMSMSmrK7eNlXLN&s=aE-DERqGRwKm6kemVr6subZ4jI7mO6so1wFy41mJZQ0&e=   stats”

and the instructions states "If you get the following response:  “command was not found” it means the sensor was not installed.
I did get that response.
I was under the impression that the script installs the sensor, but it looks it does not. Can someone help with the right way to deploy the sensor.

**Comment by cliv** [comment]
The instructions definately don't mention proofpoint urldefence - Is it possible your company security software is modifying the instructions somehow?
