### ISSUE TITLE
Sensor not appearing in CS console

### ISSUE THREAD

**Issue by MyloHarris** [cliv/cs-falcon-protect-intune#9]
Hello, I'm testing deployment on a 2020 Intel Core iMac. Enrolled the device into Intune, then into a group with the custom script uploaded and then ran the deployment script. Sensors installed, although they are not appearing in the Crowdstrike console and the Intune logs say the script ran successfully but give this error: "Error: Provisioning token format incorrect falconctl [OPTIONS] COMMAND [ARGS...] Commands: license CCID [TOKEN] [--noload|-n] license CrowdStrike Falcon sensor. Requires a valid Checksummed Customer ID (CCID). An optional provisioning token can also be provided."

I've confirmed that the Checksum customer ID is the one listed in my console. Not sure if this is the problem or why it's giving this readout.

**Comment by cliv** [comment]
does the install work with the provided CCID if you run it manually?
